ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1
sae_pwe=2
network={
    ssid="LabNet_WPA3"
    key_mgmt=SAE
    sae_password="LabPassphrase2024!"
    proto=RSN
    pairwise=CCMP
    group=CCMP
    ieee80211w=2
}
